lookup parent classes when instance class not found in metadataMap
mezzio/mezzio-hal pull request #35
Opened 2021-02-13 23:44 UTC by tobias-trozowski

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
This PR aims to provide the lookup of parent classes when the instance class is not found in metadataMap when using `ResourceGenerator::fromObject`.

When using doctrine with mezzio-hal i encountered the issue that doctrine proxy classes cannot be mapped and therefore throw an exception.

2021-03-18 14:59 UTC, tobias-trozowski commented
related issue #10

2021-05-14 15:04 UTC, weierophinney requested changes
This looks great! My only suggestions are some nit-picks around annotations - use intersection types wherever possible. phpcs no longer complains about them, and Psalm then sees them correctly as well.

2021-05-14 15:04 UTC, weierophinney commented on test/Assertions.php
> +     * @psalm-return ObjectPropertyHydrator::class|ObjectProperty::class
```suggestion
     * @psalm-return ObjectPropertyHydrator::class&ObjectProperty::class
```

(should be an intersection type)

2021-05-14 15:04 UTC, weierophinney commented on test/ResourceGeneratorTest.php
> +     */
```suggestion
    /** @var ObjectProphecy&ServerRequestInterface */
```

Simpler, and more consistent with what we do in other packages.

2021-05-14 15:04 UTC, weierophinney commented on test/ResourceGeneratorTest.php
> +     */
```suggestion
    /** @var ObjectProphecy&ContainerInterface */
```

2021-05-14 15:04 UTC, weierophinney commented on test/ResourceGeneratorTest.php
> +     */
```suggestion
    /** @var ObjectProphecy&Metadata\MetadataMap */
```

2021-05-14 16:09 UTC, weierophinney commented on test/Assertions.php
> +     * @psalm-return ObjectPropertyHydrator::class|ObjectProperty::class
Never mind - this is detailing a class string name, so union makes sense.

2021-05-14 16:14 UTC, weierophinney approved these changes
You can ignore each of my suggestions.

When using native mocks, intersection types work perfectly well, and I made the incorrect assumption that this is what was happening here. However, this component is still using Prophecy, and with Prophecy, intersections don't work. The annotations you've provided resolve issues discovered.

2021-05-14 16:15 UTC, merged