Allow latest psr/* dependencies
mezzio/mezzio-hal pull request #49
Opened 2022-01-06 13:47 UTC by geerteltink

This PR allow latest psr dependencies.

2022-01-06 14:11 UTC, Ocramius requested changes
```
PHP Fatal error:  Declaration of Mezzio\Hal\HalResource::withLink(Psr\Link\LinkInterface $link): Mezzio\Hal\HalResource must be compatible with Psr\Link\EvolvableLinkProviderInterface::withLink(Psr\Link\LinkInterface $link): static in /github/workspace/src/LinkCollection.php on line 47
```

2022-01-06 14:36 UTC, geerteltink commented
Yes I saw that. I pick straight away the most difficult one.

2022-01-11 13:02 UTC, Ocramius requested changes

2022-01-11 13:02 UTC, Ocramius commented on composer.json
> +        "psr/link": "^1.0 || ^2.0",
I guess we need to break BC to go to `^2.0` :|

2023-06-01 06:58 UTC, closed without merging